services:
  db:
    image: postgres:16
    container_name: job-tracker-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: gideon
      POSTGRES_PASSWORD: localdev
      POSTGRES_DB: job_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: