import type { Request, Response } from "express";
import { db } from "../db/index.js";
import { applications } from "../db/schema.js"; // schema definition, not data
import { eq } from "drizzle-orm"; // "equals" operator for WHERE clauses

// GET /applications — return all applications from the database
export async function listApplications(_req: Request, res: Response): Promise<void> {
  const result = await db.select().from(applications); // SELECT * FROM applications
  res.json(result);
}

// GET /applications/:id — return a single application by ID
export async function getApplication(req: Request, res: Response): Promise<void> {
  const id = parseInt(req.params.id); // route params are strings, convert to number
  const result = await db.select().from(applications).where(eq(applications.id, id)); // WHERE id = ?

  if (result.length === 0) {
    res.status(404).json({ error: "Application not found" });
    return;
  }

  res.json(result[0]); // result is always an array, grab the first (and only) row
}

// POST /applications — create a new application
export async function createApplication(req: Request, res: Response): Promise<void> {
  const { company, role, status, appliedDate, notes } = req.body; // destructure request body

  // id is auto-generated by serial, created_at by defaultNow() — don't pass either
  const result = await db.insert(applications).values({
    company,
    role,
    status,
    appliedDate,
    notes,
  }).returning(); // .returning() gives back the inserted row including generated id and created_at

  res.status(201).json(result[0]); // 201 = Created
}

// PUT /applications/:id — update an existing application
export async function updateApplication(req: Request, res: Response): Promise<void> {
  const id = parseInt(req.params.id);

  // .set(req.body) updates only the fields the client sent
  // .returning() gives back the updated row, or empty array if id not found
  const result = await db.update(applications)
    .set(req.body)
    .where(eq(applications.id, id))
    .returning();

  if (result.length === 0) {
    res.status(404).json({ error: "Application not found" });
    return;
  }

  res.json(result[0]);
}

// DELETE /applications/:id — remove an application
export async function deleteApplication(req: Request, res: Response): Promise<void> {
  const id = parseInt(req.params.id);

  // .returning() tells us if a row was actually deleted
  const result = await db.delete(applications)
    .where(eq(applications.id, id))
    .returning();

  if (result.length === 0) {
    res.status(404).json({ error: "Application not found" });
    return;
  }

  res.status(204).send(); // 204 = No Content, standard for successful DELETE
}